/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author fer_1
 */
public class Interfaz extends javax.swing.JFrame {
TokensAutomata analisisLexico;
AnalisisLexico modelo = null;
JFileChooser seleccionar = new JFileChooser();
File archivo;
FileInputStream entrada;
FileOutputStream salida;
    /**
     * Creates new form Interfaz
     */
    


    public Interfaz() {
        analisisLexico = new TokensAutomata();
        modelo = new AnalisisLexico(analisisLexico.getToken1(), analisisLexico.getLexema1());
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public String AbrirArchivo(File archivo){
        String documento="";
        try{
            entrada=new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter=(char)ascci;
                documento+=caracter;
            }
        }catch(Exception e){
        }
        return documento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1_MostrarNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_MostrarContenido = new javax.swing.JTextArea();
        jLabel1_Titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2_Analizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2_nemoticones = new javax.swing.JLabel();
        jLabel2_tiempo = new javax.swing.JLabel();
        jButton3_Comprobar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1_Titulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1_Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_Titulo.setText("Analizador Léxico Modismos y Emoticones");
        getContentPane().add(jLabel1_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 380, 20));

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));
        getContentPane().add(jTextField1_MostrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 510, 30));

        jTextArea_MostrarContenido.setColumns(20);
        jTextArea_MostrarContenido.setRows(5);
        jScrollPane2.setViewportView(jTextArea_MostrarContenido);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 360, 230));

        jLabel1_Titulo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_Titulo1.setText("Texto para análisis");
        getContentPane().add(jLabel1_Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 20));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Texto analisado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Token", "Lexema"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 230, 230));

        jButton2_Analizar.setText("ANALIZAR");
        jButton2_Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_AnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_Analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));
        getContentPane().add(jLabel2_nemoticones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 360, 30));
        getContentPane().add(jLabel2_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 230, 30));

        jButton3_Comprobar.setText("COMPROBAR");
        jButton3_Comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ComprobarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3_Comprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(seleccionar.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento=AbrirArchivo(archivo);
                    jTextArea_MostrarContenido.setText(documento);
                  jTextField1_MostrarNombre.setText(archivo.getAbsolutePath());
                }else{
                    JOptionPane.showMessageDialog(null,"Archivo no compatible");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    private void jButton2_AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_AnalizarActionPerformed
        // TODO add your handling code here
        long starttime= System.nanoTime();
        analisisLexico.Inicia();
        if (jTextArea_MostrarContenido.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Archivo vacio");
        }else{
        analisisLexico.AnalisisAutomata(jTextArea_MostrarContenido.getText());
        modelo = new AnalisisLexico(analisisLexico.getToken1(), analisisLexico.getLexema1());

        jTable1.setModel(modelo);
        long finttime= System.nanoTime();
        
         jLabel2_tiempo.setText("Tiempo"+(finttime-starttime)/1e6+"ms");
        }
 
       
    }//GEN-LAST:event_jButton2_AnalizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //        
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3_ComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ComprobarActionPerformed
        int a=0;
        int b=0;
        for(int i=0;i<jTable1.getRowCount();i++){
            if(jTable1.getValueAt(i, 0).equals("Emoji")){
                a++;
            }
            if(jTable1.getValueAt(i, 0).equals("Abreviatura")){
                b++;
            }            
            jLabel2_nemoticones.setText("Emojis=\t"+" "+a+"\tAbreviaturas=\t"+b);
        
        }
    }//GEN-LAST:event_jButton3_ComprobarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextArea_MostrarContenido.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2_Analizar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3_Comprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Titulo;
    private javax.swing.JLabel jLabel1_Titulo1;
    private javax.swing.JLabel jLabel2_nemoticones;
    private javax.swing.JLabel jLabel2_tiempo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_MostrarContenido;
    private javax.swing.JTextField jTextField1_MostrarNombre;
    // End of variables declaration//GEN-END:variables
}
